[images]
remote_images = []

[[headers]]
for = "/_astro/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[context]

  [context.production]

    [context.production.images]
    remote_images = []

    [[context.production.headers]]
    for = "/_astro/*"

      [context.production.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  [context.main]

    [context.main.images]
    remote_images = []

    [[context.main.headers]]
    for = "/_astro/*"

      [context.main.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"